spring:
  application:
    name: zadanko
  datasource:
    url: jdbc:h2:file:./testdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""  # Puste has?o dla bazy H2 w pami?ci
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # Jawne okre?lenie dialektu
  h2:
    console:
      enabled: true
      path: /h2-console  # Opcjonalne, ale dla jasno?ci
  sql:
    init:
      mode: always  # Tryb inicjalizacji danych
      platform: h2